version: "3.8"

services:
    backend: 
      build:
        context: .
        dockerfile: ./docker/Dockerfile.backend
      ports:
        - 8080:8080
      environment:
        - DATABASE_URL=postgresql://postgres:mypass@postgres:5432/my_docker_app
      depends_on:
        - postgres
    frontend:
      build: 
        context: .
        dockerfile: ./docker/Dockerfile.frontend
        # args:
        #   - DATABASE_URL="postgresql://postgres:postgres@postgres:5432/mydb?schema=public"
      ports:
        - 3000:3000
      environment:
        - DATABASE_URL=postgresql://postgres:mypass@postgres:5432/my_docker_app
      depends_on:
        - postgres
    websocket:
      build:
        context: .
        dockerfile: ./docker/Dockerfile.websocket
      ports: 
        - 8081:8081
      environment:
        - DATABASE_URL=postgresql://postgres:mypass@postgres:5432/my_docker_app
      depends_on:
        - postgres
    postgres:
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: mypass
        POSTGRES_DB: my_docker_app