version: "3.8"

services:
    backend: 
      build:
        context: .
        dockerfile: ./docker/Dockerfile.dev.be
      ports:
        - 8080:8080
      env_file:
        - ./packages/db/.env
      depends_on:
        - postgres
      volumes:
      - .:/app
      - /app/node_modules
    frontend:
      build: 
        context: .
        dockerfile: ./docker/Dockerfile.dev.fe
      env_file:
        - ./packages/db/.env
      ports:
        - 3000:3000
      depends_on:
        - postgres
      volumes:
      - .:/app
      - /app/node_modules
    websocket:
      build:
        context: .
        dockerfile: ./docker/Dockerfile.websocket
      ports: 
        - 8081:8081
      env_file:
        - ./packages/db/.env
      depends_on:
        - postgres
      volumes:
      - .:/app
      - /app/node_modules
    postgres:
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: my_pass
        POSTGRES_DB: postgres
      volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
        