FROM oven/bun:1 AS base

WORKDIR /usr/src/app
# ARG DATABASE_URL
#DONOT COPY . . as it would copy the whole directory in backend docker file
COPY ./packages  ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json


COPY ./apps/web ./apps/web


RUN bun install --no-cache
RUN bun db:generate && bun db:migrate
# RUN DATABASE_URL=$DATABASE_URL bunx turbo build --filter=web...


EXPOSE 3000

CMD ["bun", "run", "start:web"]

