FROM oven/bun:1 AS base

WORKDIR /usr/src/app

#DONOT COPY . . as it would copy the whole directory in backend docker file
COPY ./packages  ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json


COPY ./apps/ws-server ./apps/ws-server


RUN bun install
RUN bun db:generate


EXPOSE 8081

CMD ["bun", "run", "start:ws"]

