FROM oven/bun:1 AS base

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/web/package.json ./apps/web/package.json

RUN bun install

COPY ./apps/web ./apps/web

EXPOSE 3000

CMD [ "bun", "run", "docker-dev:web" ]

