FROM oven/bun:1 AS base

WORKDIR /usr/src/app

#DONOT COPY . . as it would copy the whole directory in backend docker file
COPY ./packages  ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json


COPY ./apps/http-server ./apps/http-server


RUN bun install --no-cache
RUN bun db:generate


EXPOSE 8080

CMD ["bun", "run", "start:http"]

