name: Deploy the backend
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: kunalnasa/todo-app-backend:${{ github.sha }}

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@65.0.122.248 << 'EOF'
            # Stop and remove any existing container
            sudo docker stop user_backend || true
            sudo docker rm user_backend || true

            # Pull the latest image
            sudo docker pull kunalnasa/todo-app-backend:${{ github.sha }}

            # Run the new container
            sudo docker run --name user_backend -d -p 8080:8080 -e DATABASE_URL="${{ secrets.DATABASE_URL }}" kunalnasa/todo-app-backend:${{ github.sha }}
          EOF
